name: Deploy Web (Production)

on:
  push:
    tags:
      - "web-v*.*.*"

jobs:
  deploy-web:
    name: Deploy Frontend to Production
    runs-on: web-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install PM2
        run: npm install -g pm2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Navigate to apps/web and build
        run: |
          cd apps/web
          cp ~/.env.web .env
          pnpm build

      - name: Start application with PM2
        run: |
          cd apps/web
          pm2 start pnpm --name "evolved-web" -- start
          pm2 save
